### ISSUE TITLE
Texture

### ISSUE THREAD

**Issue by GreenBuhnana** [Rivmun/FootprintParticle#21]
I dont know if you are able, but I want to be able to change the textures, or have a simple one because I am using barebones, And if this is possible, are you able to make the footprints match the rotation to where they are walking to?

**Comment by Rivmun** [comment]
About texture: I think you can make custom one as a resource pack. Path is _assets\minecraft\textures\particle\footprint_0.png_ to _..\footprint_3.png_, or _assets\footprintparticle\textures\particle\_ (not sure because I haven't done so)

About rotation: honestly and sadly, I don't know how to rotate texture.

**Comment by Rivmun** [comment]
I'm open a new issue focus on rotation, so this issue will close.
